---
- name: install python and update packages
  become: yes
  apt:
    name: python
    state: latest
    update_cache: yes

- name: upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: install nodejs
  become: yes
  apt:
    name: nodejs
    state: latest
    update_cache: yes

- name: install npm
  become: yes
  apt:
    name: npm
    state: latest
    update_cache: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
