- name: compress backend dir
  archive:
    path: /root/project/backend
    dest: /root/project/backend.tgz
  delegate_to: localhost
  become: false

- name: copy util folder to ec2 instance
  become: yes
  copy:
    src: /root/project/backend.tgz
    dest: /home/ubuntu
    owner: ubuntu

- name: extract backend.tgz into /home/ubuntu
  unarchive:
    src: /root/project/backend.tgz
    dest: /home/ubuntu

- name: copy docker-compose.yml folder to ec2 instance
  become: yes
  copy:
    src: /root/project/util/docker-compose.yml
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: install docker-compose
  become: yes
  apt:
    name: docker-compose
    state: present

- name: run postgresdb
  become: yes
  shell:
    cmd: docker-compose up -d
    chdir: /home/ubuntu/backend

- name: install npm
  shell:
    cmd: npm install
    chdir: /home/ubuntu/backend

- name: build backend
  shell:
    cmd: npm run build
    chdir: /home/ubuntu/backend

- name: run db migrations
  shell:
    cmd: npm run migrations
    chdir: /home/ubuntu/backend

- name: use pm2 to run backend
  become: yes
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 start npm --name backend -- start
